//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class CakeImportOrder
    {
        public int ID { get; set; }
        public string ImportOrderName { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string ImageOrder { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> GoodsAmount { get; set; }
        public Nullable<int> Remainder { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
